$schema: "https://json-schema.org/draft/2020-12/schema"
type: object
properties:
  sample:
    type: string
  platform:
    type: string
  fq1:
    type: string
  fq2:
    type: string
required:
  - sample
  - platform
  - fq1
  - fq2
additionalProperties: false

